# Generated by Django 3.1.7 on 2021-04-13 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_shop', '0002_kit_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='items',
            field=models.ManyToManyField(to='food_shop.Dish', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='percent',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Введите скидку в %'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kit',
            name='total_after',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Цена со скидкой'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kit',
            name='total_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена без скидки'),
        ),
    ]
